### ISSUE TITLE
Url has been moved

### ISSUE THREAD

**Issue by shirotech** [roflmuffin/node-anime-scraper#16]
Hi there,

I'm getting this error:

```bash
  test Received HTTP error retrieving URL: http://kissanime.to/AdvanceSearch +1ms
  test Retrieving fresh Cloudflare cookie. +1ms
  test Fresh Cloudflare cookie retrieved. +8s
  test HTTPError: Response code 301 (Moved Permanently)
```

Can you please change the KISS_URL to ```KISS_URL = 'http://kissanime.ru';```

That seems to fix it for me.

**Comment by roflmuffin** [comment]
Thanks, the module should already follow redirects, but it looks like it falls down when we use the cloudscraper module to get a new cookie. I should be able to implement a follow redirect on the cloudscraper module to prevent this from occurring in the future.

I've created issue #18 for the feature request.
