### ISSUE TITLE
Follow redirects when requesting new cookies

### ISSUE THREAD

**Issue by roflmuffin** [roflmuffin/node-anime-scraper#18]
KissAnime often changes domains causing issues with the module when it does so.

Implement `followRedirect` on the Cloudscraper request to resolve this.

**Comment by shirotech** [comment]
The latest cloudscraper seems to support this already at 1.4.1, a simple update in package.json would do. Mind if I do a PR?

**Comment by roflmuffin** [comment]
Of course go ahead, please increment the patch version if you do (should be at 2.1.5 afterwards), and I will publish to npm when I get a spare moment.

**Comment by roflmuffin** [comment]
Fixed by Van's PR #19. Kudos.
