### ISSUE TITLE
Video Urls empty

### ISSUE THREAD

**Issue by joshcamas** [roflmuffin/node-anime-scraper#20]
It doesn't seem to be able to scrape the video urls, is there a new protection that renders this library useless? :(

**Comment by roflmuffin** [comment]
Looks like a lot of their pages have transitioned to using third party hosts, which is a shame 👎 

It means I will probably have to re-write the video retrieving aspect so that it can retrieve direct links from those third party mirrors (OpenLoad).

They also have an option to view from the 'Beta Server', which I think is a high quality direct link (similar to how they had it before) but requires an additional page load to retrieve.

**Comment by roflmuffin** [comment]
I have just pushed through dc22f7a with a new npm version that should restore functionality on pages that still have the KA server links.

**Comment by TsukiyomiSachiko** [comment]
So I updated to the most recent version, and whilst most video_links arrays remain empty, the ones that are filled are filled with useless [gibberish](https://pastebin.com/J00WN14x).

Running: Ubuntu 17.04 with Node v4.7.2

I have also been able to reproduce this on Windows 10 running Node v6.10.0LTS

**Comment by roflmuffin** [comment]
You can take a look at [this thread](https://www.reddit.com/r/KissAnime/comments/60fbp0/the_state_of_kissanime_kodi_addons_and_how/) on how KissAnime has been steadily adding obfuscating to their site. At this point it would be a lot of work to get the package working again (though it is possible), or we could look at allowing the package to search a different site altogether (rather than KissAnime).

Let me know what you think.

**Comment by joshcamas** [comment]
Sadly, it looks like kiss is a dead end. Now there isn't only a simple cloudflare layer, but also captchas that we won't be able to crack. I vote we look into another site. A month ago I was working on one for gogo anime, almost got it too, just had a few bugs. Maybe look into gogo?

**Comment by TsukiyomiSachiko** [comment]
gogoanime.io also seems to have a fairly bot-friendly download button, I think it might be a good alternative for kiss, as I don't really see kiss working out either, with all the obscurity and security and all... I don't think there's harm in trying, at least.

Side note: gogo does seem to have a little less content than kiss does, so I'll also keep looking for sites that might contain more content

**Comment by roflmuffin** [comment]
Hey guys,

I have developed a prototype new version in the [nextgen branch](https://github.com/roflmuffin/node-anime-scraper/tree/nextgen), so please take a look and let me know if you run into any issues.

You can install the new package with the command `npm install git://github.com/roflmuffin/node-anime-scraper.git#nextgen`.

I've literally whipped this up after dinner tonight, and at the moment it only implements the 'Vidstreaming' video source. I will try and implement tests tomorrow, and once successful will push to npm registry.

Would love to hear your thoughts :thumbsup:

**Comment by TsukiyomiSachiko** [comment]
I quickly browsed the code, and it looks good to me, can't test tho, as NPM somehow doesn't like pulling from git, and pulling it myself and requiring it locally throws more errors my way than I am willing to handle, so I'll be waiting for the push to the npm registry

You worked pretty damn fast btw, great job :+1:

**Comment by roflmuffin** [comment]
Alrighty, version 3 has just been pushed, you should be able to grab it from the registry now.

There are some basic tests in there that test functionality (but not failure of functionality yet). 

The API should function exactly the same as the previous version so no changes needed there, but of course the selection of anime may be limited as we are no longer using Kiss.

**Comment by TsukiyomiSachiko** [comment]
It seems that setDelay(milliSeconds) is no longer part of Anime? Is this intentional or a bug? Did it move somewhere?

**Comment by TsukiyomiSachiko** [comment]
I also noticed that episode.video_links was renamed to episode.videoLinks, quick change, but good to know :P

Anyways, I love that it works again, I just hope you might be able to add support for the rest of the video providers soon too, as I now also recieve empty arrays for some episodes that don't have anything uploaded to Vidstreaming

**Comment by roflmuffin** [comment]
Thanks for the comments.

- The `bottleneck` npm package was causing issues with my test suite so its disabled for the moment until I can find another rate limiting package. To be honest I wasn't happy with the package as it was in v2, was a bit of a hack.
- video_links was changed to videoLinks, I totally forgot about that. I believe I changed it to conform to ES6 AirBNB ([camelcase](http://eslint.org/docs/rules/camelcase))
- I would like to add the other video providers as well. Do you have an example episode link I can take a look at where there is no Vidstreaming link? I would like to add this to the tests but couldn't find any without Vidstreaming lol

**Comment by TsukiyomiSachiko** [comment]
Out of the top of my head I think I was missing episodes 1-3 of Gabriel Dropout, the arrays were empty so I assumed there was no vidstreaming source,  as it also wasn't listed in the downloads on the website. I could look around for more if that helps, I have a lot of anime I need to download anyways...

**Comment by roflmuffin** [comment]
Looking at episode 1, it looks like it still Iframes to Vidstreaming, but then Vidstreaming then has an Iframe itself for Openload. 

Looks like I'll need to add functionality to determine if Vidstreaming has an iframe then its a dead end and to use another provider.

**Comment by joshcamas** [comment]
Ah, I remember. Basically once you load the iframe, to gain access to the video you have to run a bit of Javascript. I can check what it is if you guys need it.
