### ISSUE TITLE
Dosen't work.

### ISSUE THREAD

**Issue by fir3z** [roflmuffin/node-anime-scraper#27]
Literally does nothing.

**Comment by TsukiyomiSachiko** [comment]
Blame kissanime, they changed their system and added captchas, also, I don’t believe this project is actively maintained, Fox it yourself if ya wanna use it

On 31 Jan 2019, at 21:46, FirezYT <notifications@github.com<mailto:notifications@github.com>> wrote:


Literally does nothing.

**Comment by roflmuffin** [comment]
What @JRoffel said is correct. The package originally used KissAnime but they added Captchas to pretty much every page load which kind of killed the package.

I then changed it to use GogoAnime but now there are tons of problems with trying to retrieve video links from third party video hosts (like Mp4upload etc.) which leaves it dead in the water.

On a side note, I can't believe there are people in this world who go into the issues section of a repo that had its last commit 2 years ago with such an unhelpful and useless comment.
