### ISSUE TITLE
Sorry for the "Dosen't work" issue. Info in a comment.

### ISSUE THREAD

**Issue by fir3z** [roflmuffin/node-anime-scraper#28]
Can you please change the scraper to work off of a simple anime website such as AnimeHeaven.co ? Due to GogoAnime using Vidstreaming and other mirrors, the video links don't show up at all.

**Comment by roflmuffin** [comment]
I've had a look at the website, looks like it should be fairly simple to setup the scraper to work with that page, I'll look into it for a v4 package.
