### ISSUE TITLE
Did This Stop working

### ISSUE THREAD

**Issue by Wolfkid200444** [roflmuffin/node-anime-scraper#33]
recently this scraper seems to stop working for some reason heres are the results im getting

```
Episode {
  name: 'EP 1',
  url: 'https://gogoanime.io/naruto-episode-1',
  videoLinks: null
}
```

**Comment by roflmuffin** [comment]
Hey thanks for reporting this issue, I've pushed a new version (npm ver 3.1.2) that should fix this issue.
